# Generated by Django 5.2.1 on 2026-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_admin_pick',
            field=models.BooleanField(default=False),
        ),
    ]
